# Generated by Django 2.2.6 on 2019-11-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_shop', '0002_auto_20191107_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
