# Generated by Django 2.2.6 on 2019-11-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_shop', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriotion',
            new_name='description',
        ),
    ]
