# Generated by Django 2.2.6 on 2019-11-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_shop', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='Online_shop.CartItem'),
        ),
    ]
